// TODO: check for false positive detections per pattern
// these patterns are matched against popup-like elements or full document text to detect unknown cookie popups
export const DETECT_PATTERNS = [
    /accept cookies/gi,
    /accept all/gi,
    /reject all/gi,
    /only necessary cookies/gi, // "only necessary" is probably too broad
    /(?:by continuing.{0,100}cookie)|(?:cookie.{0,100}by continuing)/gi,
    /(?:by continuing.{0,100}privacy)|(?:privacy.{0,100}by continuing)/gi,
    /by clicking.{0,100}(?:accept|agree|allow)/gi,
    /we (?:use|serve)(?: optional)? cookies/gi,
    /we are using cookies/gi,
    /use of cookies/gi,
    /(?:this|our) (?:web)?site.{0,100}cookies/gi,
    /cookies (?:and|or) .{0,100} technologies/gi,
    /such as cookies/gi,
    /read more about.{0,100}cookies/gi,
    /consent to.{0,100}cookies/gi,
    /we and our partners.{0,100}cookies/gi,
    /we.{0,100}store.{0,100}information.{0,100}such as.{0,100}cookies/gi,
    /store and\/or access information.{0,100}on a device/gi,
    /personalised ads and content, ad and content measurement/gi,

    // it might be tempting to add the patterns below, but they cause too many false positives. Don't do it :)
    // /cookies? settings/i,
    // /cookies? preferences/i,

    // FR
    /utilisons.{0,100}des.{0,100}cookies/gi,
    /nous.{0,100}utilisons.{0,100}des/gi,
    /des.{0,100}cookies.{0,100}pour/gi,
    /des.{0,100}informations.{0,100}sur/gi,
    /retirer.{0,100}votre.{0,100}consentement/gi,
    /accéder.{0,100}à.{0,100}des/gi,
    /à.{0,100}des.{0,100}informations/gi,
    /et.{0,100}nos.{0,100}partenaires/gi,
    /publicités.{0,100}et.{0,100}du.{0,100}contenu/gi,
    /utilise.{0,100}des.{0,100}cookies/gi,
    /utilisent.{0,100}des.{0,100}cookies/gi,
    /stocker.{0,100}et.{0,100}ou.{0,100}accéder/gi,
    /consentement.{0,100}à.{0,100}tout.{0,100}moment/gi,
    /votre.{0,100}consentement/gi,
    /accepter.{0,100}tout/gi,
    /utilisation.{0,100}des.{0,100}cookies/gi,
    /cookies.{0,100}ou.{0,100}technologies/gi,
    /acceptez.{0,100}l.{0,100}utilisation/gi,
    /continuer sans accepter/gi,
    /tout refuser/gi,
    /(?:refuser|rejeter) tous les cookies/gi,
    /je refuse/gi,
    /refuser et continuer/gi,
    /refuser les cookies/gi,
    /seulement nécessaires/gi,
    /je désactive les finalités non essentielles/gi,
    /cookies essentiels uniquement/gi,
    /nécessaires uniquement/gi,

    // DE
    /wir.{0,100}verwenden.{0,100}cookies/gi,
    /wir.{0,100}und.{0,100}unsere.{0,100}partner/gi,
    /zugriff.{0,100}auf.{0,100}informationen.{0,100}auf/gi,
    /inhalte.{0,100}messung.{0,100}von.{0,100}werbeleistung.{0,100}und/gi,
    /cookies.{0,100}und.{0,100}andere/gi,
    /verwendung.{0,100}von.{0,100}cookies/gi,
    /wir.{0,100}nutzen.{0,100}cookies/gi,
    /verwendet.{0,100}cookies/gi,
    /sie.{0,100}können.{0,100}ihre.{0,100}auswahl/gi,
    /und.{0,100}ähnliche.{0,100}technologien/gi,
    /cookies.{0,100}wir.{0,100}verwenden/gi,

    /alles?.{0,100}ablehnen/gi,
    /(?:nur|nicht).{0,100}(?:zusätzliche|essenzielle|funktionale|notwendige|erforderliche).{0,100}(?:cookies|akzeptieren|erlauben|ablehnen)/gi,
    /weiter.{0,100}(?:ohne|mit).{0,100}(?:einwilligung|zustimmung|cookies)/gi,
    /(?:cookies|einwilligung).{0,100}ablehnen/gi,
    /nur funktionale cookies akzeptieren/gi,
    /optionale ablehnen/gi,
    /zustimmung verweigern/gi,

    // NL
    /gebruik.{0,100}van.{0,100}cookies/gi,
    /(?:we|wij).{0,100}gebruiken.{0,100}cookies.{0,100}om/gi,
    /cookies.{0,100}en.{0,100}vergelijkbare/gi,

    /(?:alles|cookies).{0,100}(?:afwijzen|weigeren|verwerpen)/gi,
    /alleen.{0,100}noodzakelijke?\b/gi,
    /cookies weigeren/gi,
    /weiger.{0,100}(?:cookies|alles)/gi,
    /doorgaan zonder (?:te accepteren|akkoord te gaan)/gi,
    /alleen.{0,100}(?:optionele|functionele|functioneel|noodzakelijke|essentiële).{0,100}cookies/gi,
    /wijs alles af/gi,

    // Spanish (ES)
    /(usamos|utilizar?|utilizamos|usiamo)( (tanto|las))?.{0,20}cookie/gi,
    /utilitzem galetes/gi,
    /cookies propias y de/gi,
    /nosotros y nuestros( \d+)? (socios|proveedores).{0,180} cookies/gi,
    /cookie.{0,30} utiliza/i,
    /almacenar la información en un dispositivo y\/?o acceder a ella/i,
    /al hacer clic.{0,80}aceptar/i,
    /est[ea] (sitio|página|web)( web)?( también)? (usa|utiliza|requiere del uso de|se sirven|emplea) cookies?/i,
    /cookies.{0,80}son necesarias/i,
    /cookies pròpies i de tercers/gi,
    /recopilamos y almacenamos datos de usted y de su dispositivo/gi,
    /utilizamos tecnolog[ií]as como las cookies/i,
    /\busa cookies de google\b/i,
    /al utilizar nuestro sitio web.{0,80}cookie/i,
    /acepta.{0,80} uso de cookies/i,
    /(si|al) contin[úu]a[sr]?( navegando)?.{0,100} cookie/i,
    /\b(hacemos|hace) uso de cookies\b/i,
    /si haces? clic.{0,20}acept/i,
    /navegando.{0,100}cookie/i,

    // Polish (PL)
    /strona.{0,50} używa (ciasteczek|cookie)/gi,
    /(używamy|stosujemy|stosuje|wykorzystujemy|wykorzyst(uje|ywane))( są)?.{0,20} plik(i|ów|ach) cookie/i,
    /wykorzystują .{0,100}cookie/gi,
    /zgodą my i nasi partnerzy możemy wykorzystywać precyzyjne dane geolokalizacyjne i identyfikację/gi,
    /uzyskujemy dostęp i przechowujemy informacje na urządzeniu/gi,
    /przechowywanie informacji na urządzeniu lub dostęp do nich/i,
    /używamy plików.{0,20}cookie/i,
    /korzystamy z technologii, takich jak pliki cookie/gi,
    /przechowywać i uzyskiwać dostęp do informacji na twoich urządzeniach/gi,
    /przetwarzamy.{0,80} cookie/i,
    /za pomocą plików cookies.{0,100} my lub nasi partnerzy/gi,
    /używa plik[ió]w? cookie/gi,
    /niektóre pliki cookies/i,
    /korzystamy.{0,50} cookies/i,
    /(używać|używamy).{0,80} (ciasteczek|cookie)/i,
    /ta strona korzysta z ciasteczek/i,
    /przechowywanie plików cookie na swoim urządzeniu/i,
    /korzysta.{0,80} plików cookie/i,
    /cele przetwarzania twoich danych przez zaufanych partnerów iab/i,
    /pliki cookies i pokrewne im technologie umożliwiają poprawne działanie strony i pomagają nam dostosować ofertę do twoich potrzeb/i,
    /dzięki (plikom cookie|ciasteczkom|cookie)/i,
];

const REJECT_PATTERNS_ENGLISH = [
    // e.g. "i reject cookies", "reject all", "reject all cookies", "reject cookies", "deny all", "deny all cookies", "refuse", "refuse all", "refuse cookies", "refuse all cookies", "deny", "reject all and close", "deny all and close", "reject non-essential cookies", "reject all non-essential cookies and continue", "reject optional cookies", "reject additional cookies", "reject targeting cookies", "reject marketing cookies", "reject analytics cookies", "reject tracking cookies", "reject advertising cookies", "reject all and close", "deny all and close", "i reject all (except strictly necessary)"
    // note that "reject and subscribe" and "reject and pay" are excluded
    /^\s*(i)?\s*(reject|deny|refuse|decline|disable)\s*(all)?\s*(non-essential|optional|additional|targeting|analytics|marketing|unrequired|non-necessary|extra|tracking|advertising)?\s*(cookies)?\s*(\(?\s*except\s+(strictly\s+)?(necessary|essential)\s*\)?)?\s*$/is,

    // e.g. "i do not accept", "i do not accept cookies", "do not accept", "do not accept cookies"
    /^\s*(i)?\s*do\s+not\s+accept\s*(cookies)?\s*$/is,

    // e.g. "continue without accepting", "continue without agreeing", "continue without agreeing →"
    /^\s*(continue|proceed|continue\s+browsing)\s+without\s+(accepting|agreeing|consent|cookies|tracking)(\s*→)?\s*$/is,

    // e.g. "strictly necessary cookies only", "essential cookies only", "required only", "use necessary cookies only", "essentials only"
    // note that "only" is required
    /^\s*(use|accept|allow|continue\s+with)?\s*(strictly)?\s*(necessary|essentials?|required)?\s*(cookies)?\s*only\s*$/is,

    // e.g. "allow essential cookies", "allow necessary", "allow essentials", "allow essentials only"
    // note that "essential" is required
    /^\s*(use|accept|allow|continue\s+with)?\s*(strictly)?\s*(necessary|essentials?|required)\s*(cookies)?\s*$/is,

    // e.g. "accept only essential cookies", "use only necessary cookies", "allow only essential", "only essentials", "continue with only essential cookies"
    // note that "only" is required
    /^\s*(use|accept|allow|continue\s+with)?\s*only\s*(strictly)?\s*(necessary|essentials?|required)?\s*(cookies)?\s*$/is,

    // e.g. "do not sell or share my personal information", "do not sell my personal information"
    // often used in CCPA
    /^\s*do\s+not\s+sell(\s+or\s+share)?\s*my\s*personal\s*info(rmation)?\s*$/is,

    'allow selection',
    'disagree and close',

    // These are impactful, but look error-prone
    // // e.g. "disagree"
    /^(i)?\s*disagree\s*(and\s+close)?$/i,
    // // e.g. "i do not agree"
    // /^\s*(i\s+)?do\s+not\s+agree\s*$/i,
    'no',
    /^no,? thanks$/is,
    /^opt[ -]out$/is,
];

const REJECT_PATTERNS_DUTCH = [
    'weigeren',
    'alles afwijzen',
    'alleen noodzakelijke cookies',
    'afwijzen',
    'alles weigeren',
    'cookies weigeren',
    'alleen noodzakelijk',
    'weiger',
    'weiger cookies',
    'selectie toestaan',
    'doorgaan zonder te accepteren',
    'alleen functionele cookies',
    'alleen functioneel',
    'alleen noodzakelijke',
    'alleen essentiële cookies',
    'functioneel',
    'alle cookies verwerpen',
    'doorgaan zonder akkoord te gaan',
    'weiger alles',
    'nee, bedankt',
    'alle cookies weigeren',
    'weiger alle cookies',
    'alleen noodzakelijke cookies accepteren',
    'alleen strikt noodzakelijk',
    'ik weiger',
    'optionele cookies weigeren',
    'alle weigeren',
    'accepteer alleen noodzakelijke cookies',
    'alleen functionele cookies accepteren',
    'enkel noodzakelijke cookies',
    'niet accepteren',
    'weiger niet-essentiële cookies',
    'weiger niet-noodzakelijke cookies',
    'wijs alles af',
    'alle cookies afwijzen',
    'alleen vereiste cookies',
    'cookies afwijzen',
    'doorgaan zonder accepteren',
    'hier weigeren',
    'weiger alle',
    'aanvaard enkel essentiële cookies',
    'aanvullende cookies weigeren',
    'accepteren weigeren',
    'alle afwijzen',
    'alle niet functionele afwijzen',
    'alle optionele weigeren',
    'alleen noodzakelijke accepteren',
    'alleen strikt noodzakelijke cookies',
    'allen afwijzen',
    'clear weigeren',
    'enkel functioneel',
    'enkel noodzakelijke cookies aanvaarden',
    'functioneel altijd actief',
    'nee, accepteer alleen de noodzakelijke',
    'nee, geen cookies a.u.b.',
    'nee, weiger cookies',
    'nee, weigeren',
    'niet-noodzakelijke cookies weigeren',
    'optioneel afwijzen',
    'tracking cookies weigeren',
    'weigeren cookies',
    'weigeren?',
    'weigeren.',
    'strikt noodzakelijk',
    'weiger optionele cookies',
    'noodzakelijke cookies',
    'essentiële cookies',
    'ga verder zonder aanvaarden',
    'doorgaan zonder cookies',
    'accepteer noodzakelijke cookies',
    'noodzakelijke',
    'indien je enkel technisch noodzakelijke cookies wenst te accepteren, klik dan hier',
    'weiger',
    'alleen de noodzakelijke cookies',
    'alleen noodzakelijk',
    'alleen verplichte cookies',
    'ik wil alleen minimale cookies',
    'doorgaan zonder te accepteren',
    'geen cookies toestaan',
    'liever geen cookies',
    'nee, geen persoonlijke cookies',
    'nee, liever geen cookies',
    'ga door zonder te accepteren',
    'verder zonder accepteren',
    'essentiële accepteren',
    'functionele cookies',
    'strikt noodzakelijke cookies',
    'alleen basic cookies',
    'alleen basiscookies',
    'alleen standaard cookies',
    'alle cookies verwerpen',
    'noodzakelijk',
    'noodzakelijk cookies accepteren',
    'noodzakelijke cookies accepteren',
    'accepteer alleen noodzakelijk',
    'enkel noodzakelijke toestaan',
    'enkel strikt noodzakelijke cookies',
    'ik wijs ze liever af',
    'ik weiger cookies',
    'ik weiger optionele cookies',
    'weiger alle cookies',
    'weiger alle niet-noodzakelijke cookies',
    'weiger alle onnodige cookies',
    'weiger alle optionele',
    'weiger alles',
    'weiger targeting en third party cookies.',
];

const REJECT_PATTERNS_FRENCH = [
    'continuer sans accepter',
    'tout refuser',
    'refuser',
    'refuser tous les cookies',
    'non merci',
    'interdire tous les cookies',
    'je refuse',
    'refuser tout',
    'tout rejeter',
    'refuser et continuer',
    'rejeter',
    'refuser les cookies',
    'cookies nécessaires uniquement',
    'seulement nécessaires',
    'rejeter tout',
    'refuser les cookies optionnels',
    'je désactive les finalités non essentielles',
    'refuser les cookies non nécessaires',
    'rejeter tous les cookies',
    'cookies essentiels uniquement',
    'nécessaires uniquement',
    'refuser les cookies non essentiels',
    'tout refuser et fermer',
    'tout refuser sauf les cookies techniques',
    'continuer sans accepter x',
    'je refuse lutilisation de cookies',
    'non merci, seulement des cookies techniques',
    'non, tout refuser',
    'refuser tous les cookies non nécessaires',
    'rejeter les cookies',
    'uniquement les essentiels',
    'refuser tous',
    'accepter uniquement les nécessaires',
    'allow anonymous analytics',
    'autoriser les cookies essentiels uniquement',
    'autoriser uniquement les nécessaires',
    'cookies essentiels seulement',
    'cookies nécessaires seulement',
    'cookies techniques uniquement',
    'je préfère les rejeter',
    'je refuse :(',
    'je refuse les cookies',
    'je refuse tous les cookies',
    'je refuse tout',
    'ne pas accepter',
    'non, accepter les nécessaires uniquement',
    'refuser (sauf cookies nécessaires)',
    'refuser ce cookie',
    'refuser les coockies',
    'refuser les cookies facultatifs',
    'refuser tout, sauf les cookies techniques',
    'refuser toutes',
    'refuser toutes les options',
    'rejeter la bannière',
    'rejeter les cookies non essentiels',
    'rejeter les cookies optionnels',
    'rejeter tous les non fonctionnels',
    'rejeter tout optionnel',
    'tout refuser, sauf les cookies techniques',
    'uniquement nécessaires',
    'x continuer sans accepter',
    'strictement nécessaires',
    'utiliser uniquement les cookies nécessaires',
    'cookies nécessaires',
    'accepter uniquement les cookies essentiels',
    'accepter les cookies nécessaires',
    'uniquement les cookies nécessaires',
    'autoriser uniquement les cookies essentiels',
    'autoriser uniquement les cookies nécessaires',
    'si vous ne souhaitez pas accepter les cookies à lexception des cookies techniquement nécessaires, veuillez cliquer ici',
    'cookies strictement nécessaires',
    'accepter les cookies strictement nécessaires',
    'autoriser les cookies essentiels',
    'non, merci, uniquement les cookies nécessaires',
    'indispensable uniquement',
    'uniquement autoriser les cookies essentiels',
    'utiliser que les cookies nécessaires',
    'uniquement les sdk nécessaires',
    'uniquement nécessaire',
    'utiliser uniquement les cookies fonctionnels',
    'refus',
    'refusez',
    'naccepter que les cookies indispensables',
    'naccepter que les cookies nécessaires',
    'naccepter que les cookies techniques',
    'nécessaires seulement',
];

const REJECT_PATTERNS_GERMAN = [
    'ablehnen',
    'alle ablehnen',
    'nur notwendige cookies',
    'nur essenzielle cookies akzeptieren',
    'nur notwendige cookies verwenden',
    'nur technisch notwendige',
    'nur essentielle cookies akzeptieren',
    'alles ablehnen',
    'nur notwendige',
    'alle cookies ablehnen',
    'weiter ohne einwilligung',
    'mit diesem button wird der dialog geschlossen. seine funktionalität ist identisch mit der des buttons nur essenzielle cookies akzeptieren.',
    'cookies ablehnen',
    'optionale cookies ablehnen',
    'nur erforderliche cookies',
    'einwilligung ablehnen',
    'nur erforderliche',
    'nur notwendige cookies zulassen',
    'nur funktionale cookies akzeptieren',
    'nur notwendige cookies akzeptieren',
    'nur notwendige technologien',
    'verweigern',
    'webanalyse ablehnen',
    'weiter ohne zustimmung',
    'optionale ablehnen',
    'nur notwendige akzeptieren',
    'nur funktionale cookies',
    'mit diesem button wird der dialog geschlossen. seine funktionalität ist identisch mit der des buttons ablehnen.',
    'nur notwendige cookies erlauben',
    'zustimmung verweigern',
    'nein, danke',
    'nur erforderliche cookies akzeptieren',
    'zusätzliche cookies ablehnen',
    'ablehnen und nur essenzielle cookies akzeptieren',
    'nicht erforderliche ablehnen',
    'nicht essenzielle cookies daten ablehnen',
    'nur technisch notwendige cookies',
    'nur technisch notwendige cookies akzeptieren',
    'ablehnen speichern',
    'alle funktionen ablehnen',
    'alle optionalen cookies ablehnen',
    'alles verweigern',
    'mit erforderlichen einstellungen fortfahren',
    'nicht notwendige ablehnen',
    'notwendige cookies akzeptieren',
    'nur erforderliche technologien',
    'nur essenzielle cookies',
    'nur essenzielle cookies erlauben',
    'technisch nicht notwendige cookies ablehnen',
    'tippen sie zum ablehnen bitte hier',
    'ablehnen deny',
    'fortfahren ohne zu akzeptieren',
    'nur erforderliche akzeptieren',
    'nur notwendige erlauben',
    'ablehnen ...nur technisch notwendige cookies verwendet werden',
    'ablehnen (außer notwendige cookies)',
    'ablehnen und fortfahren',
    'ablehnen und schließen',
    'ablehnen: nur grundfunktionen',
    'akzeptieren nur notwendige cookies',
    'alle ablehnen (außer notwendige cookies)',
    'alle nicht essenziellen cookies ablehnen',
    'alle nicht notwendigen cookies ablehnen',
    'alle optionale ablehnen',
    'alle optionalen ablehnen',
    'alle verweigern',
    'analyse cookies ablehnen',
    'cookie einstellungenablehnen',
    'erforderliche cookies akzeptieren',
    'erforderliche cookies zulassen',
    'externe inhalte ablehnen',
    'mit diesem button wird der dialog geschlossen. seine funktionalität ist identisch mit der des buttons ablehnen und nur essenzielle cookies akzeptieren.',
    'mit diesem button wird der dialog geschlossen. seine funktionalität ist identisch mit der des buttons nicht-essenzielle cookies verweigern.',
    'mit diesem button wird der dialog geschlossen. seine funktionalität ist identisch mit der des buttons nur essenzielle akzeptieren.',
    'mit erforderlichen cookies fortfahren',
    'mit notwendigen fortfahren',
    'nein, bitte nicht',
    'nein, ich stimme nicht zu',
    'nicht funktionale cookies ablehnen',
    'nicht notwendige cookies ablehnen',
    'nicht-essenzielle cookies ablehnen',
    'nicht-essenzielle cookies verweigern',
    'notwendige cookies zulassen',
    'nur erforderliche cookies erlauben',
    'nur erforderliche cookies setzen',
    'nur erforderliche cookies verwenden',
    'nur essenzielle akzeptieren',
    'nur notwendige cookies annehmen',
    'nur notwendige cookies speichern',
    'nur notwendige cookies verwenden.',
    'nur notwendige funktionscookies akzeptieren',
    'nur notwendigen cookies zustimmen',
    'nur notwendiges akzeptieren',
    'nur wesentliche cookies annehmen',
    'opt. cookies ablehnen',
    'optionale dienste ablehnen',
    'optionale tools ablehnen',
    'sie alle cookies ablehnen',
    'technisch notwendige annehmen',
    'nur essentielle cookies',
    'nur essentielle',
    'nur funktionale akzeptieren',
    'nur technisch notwendige akzeptieren',
    'nur technisch notwendige daten und cookies ...',
    'nur technisch notwendige zulassen',
    'nur wesentliche',
    'ohne einverständnis fortfahren',
    'ohne einwilligung',
    'ohne zustimmung fortfahren',
    'ohne zustimmung weiter',
    'weiter mit essentiellen cookies',
    'weiter ohne annahme',
    'weiter ohne statistische analyse-cookies',
    'weiter ohne statistische cookies',
    'wesentliche cookies',
    'fortfahren ohne zustimmung',
];

const REJECT_PATTERNS_ITALIAN = [
    'rifiuta',
    'rifiuta cookies',
    'rifiuta i cookie',
    'rifiuta i cookies',
    'rifiuta tutti i cookie',
    'rifiuta tutti i cookies',
    'rifiuta cookie non necessari',
    'rifiuta i cookie non tecnici',
    'rifiuta non necessari',
    'rifiuta tutto',
    'rifiuta tutti',
    'rifiuta e chiudi',
    'chiudi rifiuta tutti i cookie',
    'chiudi e rifiuta tutti i cookie',
    'chiudi e rifiuta tutto',
    'nega',
    'nega tutti',
    'negare',
    'non accetto',
    'accetta solo i necessari',
    'usa solo i cookie necessari',
    'accetta solo necessari',
    'solo necessari',
    'continua senza accettare x',
    'continua senza accettare',
    'rifiutare',
    'rifiutare i cookie',
    'rifiutare tutti i cookie',
    'rifiutare tutti',
    'rifiutare e continuare',
    'installa solo i cookie strettamente necessari',
    'solo cookies tecnici',
    'accetta necessari',
    'solo cookie tecnici',
    'solo cookie necessari',
    'strettamente necessari',
    'tecnici',
    'accetta solo cookie di navigazione',
    'chiudi e prosegui solo con i cookies tecnici necessari',
    'consenti solo i cookie tecnici',
    'solo cookie essenziali',
    'blocca i cookie non essenziali',
    'accetta i cookie necessari',
    'accetta solo cookie tecnici',
    'accetta solo i cookie essenziali',
    'accetta solo i cookie necessari',
    'accetta solo i necessary',
    'accetta i cookie essenziali',
    'accetta cookie tecnici',
    'necessari',
    'usa solo i cookie tecnici',
    'usa solo i necessari',
    'rifiuto',
    'essenziali',
    'accetta cookie essenziali',
    'accetta cookie necessari',
    'accetta solo cookie essenziali',
    'accetta solo cookie necessari',
    'rifiuta cookie non necessari',
    'rifiuta cookie non essenziali',
    'rifiuta i cookie non necessari',
    'rifiuta i cookie non essenziali',
    'rifiuta tutti i cookie e chiudi',
    'rifiuta tutto e chiudi',
    'rifiuta tutti i cookie chiudi',
    'continuare senza accettare',
    'rifiutare cookies',
    'rifiutare i cookies',
    'rifiutare non necessari',
    'rifiutare tutto',
    'rifiutare e chiudere',
    'solo essenziali',
    'solo tecnici',
    'negare tutti',
];

const REJECT_PATTERNS_BRAZILIAN_PORTUGUESE = [
    // (deny)
    /^\s*(rejeitar|recusar|desativar|bloquear|negar|não\s*aceito|não \s*aceitar)\s*$/is,

    // (proceed) (without accepting)
    /^\s*(continuar|prosseguir|seguir)\s*(sem\s*aceitar)\s*$/is,

    // (deny) (everything) (optional)
    /^\s*(rejeitar|recusar|desativar|bloquear|negar|não\s*aceito|não \s*aceitar)\s*(tudo|o)?\s*(opcional|(não[-\s](essencial|funcional|obrigatório|necessário)))?\s*$/is,

    // (deny) (all) (the) (optional) (cookies)
    /^\s*(rejeitar|recusar|desativar|bloquear|negar|não\s*aceito|não \s*aceitar)\s*(todos)?\s*(os)?\s*(cookies)?\s*(opcionais|(não[-\s](essenciais|funcionais|obrigatórios|necessários)))?\s*$/is,

    // (accept) (only) (the) (essential)
    /^\s*(aceitar|utilizar)?\s*(apenas|somente|só)?\s*(o)?\s*(essencial|funcional|obrigatório|necessário)\s*$/is,

    // (accept) (only) (the) (essential) (cookies)
    /^\s*(aceitar|utilizar)?\s*(apenas|somente|só)?\s*(os)?\s*(cookies)?\s*(essenciais|funcionais|obrigatórios|necessários)\s*$/is,
];

const REJECT_PATTERNS_SPANISH = [
    'rechazar',
    'rechazar todo',
    'rechazar todas',
    'denegar',
    'rechazar cookies',
    'rechazarlas todas',
    'no acepto',
    'rechazar todas las cookies',
    'rechazar y cerrar',
    'denegar todas',
    'solo necesarias',
    'rechazar cookies opcionales',
    'rechazar opcionales',
    'cookies estrictamente necesarias',
    'aceptar sólo necesarias',
    'continuar sin aceptar',
    'denegar todo',
    'clear rechazar cookies',
    'configurar rechazar cookies',
    'denegar cookies',
    'rechazar y continuar',
    'rechazar las cookies',
    'clear rechazar',
    'denegar todas las cookies',
    'rechazar cookies no esenciales',
    'rechazarlas',
    'no, no acepto',
    'permitir sólo necesarias',
    'rechazar cookies adicionales',
    'rechazar cookies analíticas',
    'rechazar no necesarias',
    'rechazar opcional',
    'rechazar todo lo opcional',
    'solo cookies estrictamente necesarias',
    'solo esenciales',
    'x rechazar todas las cookies',
    'solo usar cookies necesarias',
    'solo cookies necesarias',
    'declinar',
    'aceptar solo las cookies esenciales',
    'necesarias',
    'aceptar cookies opcionales',
    'aceptar solo lo necesario',
    'solo funcionales',
    'declinar y cerrar',
    'déclin',
    'declina',
    'declinar consentimiento',
    'declinar todas',
    'solo las cookies necesarias',
    'només sutilitzen cookies quan és necessari',
    'no, sólo las estrictamente necesarias',
    'solo las necesarias',
    'acceptar només les necessàries',
    'acepta solo las necesarias',
    'aceptar solo lo esencial',
    'aceptar las obligatorias',
    'permitir solo cookies técnicas',
    'cookies técnicas',
    'permitir solo cookies técnicas',
    'usar solo cookies técnicas',
    'aceptar solo las esenciales',
    'no aceptar',
    'rexeitar todas',
    'no consentir',
    'ukatu',
    /^denak? baztertu|ukatu guztiak$/,
    'no, gracias',
    'revocar consentimiento',
    'rebutjar',
    'rebutja-ho tot',
    'rexeitar cookies',
    'sólo cookies propias',
    'aceptar solo cookies necesarias',
    'rebutja-les',
    'rebutjar cookies',
    'rechazo',
    'rebutjar tot',
    'no permitir',
    'sólo las cookies necesarias',
    'rebutja-les totes',
    'aceptar necesarias',
    'no, gràcies',
    'refusar i tancar',
    'no gracias',
    'rechazar todas cookies',
    'pulsa aquí para desactivar las cookies opcionales',
    'rebutjar-les totes',
    'rebutjar totes',
    'ukatu cookieak',
    'ukatu dena',
    'guztiak ukatu',
];

const REJECT_PATTERNS_SWEDISH = [
    'avvisa',
    'endast nödvändiga',
    'avvisa alla',
    'endast nödvändiga cookies',
    'neka',
    'neka alla',
    'avvisa allt',
    'avvisa alla cookies',
    'tillåt bara nödvändiga cookies',
    'bara nödvändiga',
    'bara nödvändiga cookies',
    'tillåt bara nödvändiga kakor',
    'endast nödvändiga kakor',
    'tillåt endast nödvändiga',
    'fortsätt utan att acceptera',
    'godkänn endast nödvändiga',
    'acceptera endast nödvändiga',
    'avvisa cookies',
    'tillåt endast nödvändiga kakor',
    'acceptera endast nödvändiga cookies',
    'neka kakor',
    'bara nödvändiga kakor',
    'neka alla cookies',
    'använd endast nödvändiga',
    'avvisa alla utom nödvändiga',
    'hantera eller avvisa',
    'neka alla utom nödvändiga kakor',
    'neka och stäng',
    'tillåt bara nödvändiga tjänster',
    'avvisa alla utom nödvändiga kakor',
    'avvisa alla valfria',
    'godkänn bara nödvändiga cookies',
    'acceptera endast nödvändiga kakor',
    'använd endast nödvändiga cookies',
    'avvisa alla kakor',
    'avvisa alla valmöjligheter',
    'avvisa ej nödvändiga',
    'avvisa icke-nödvändiga',
    'förneka',
    'godkänn bara nödvändiga',
    'godkänn bara nödvändiga kakor',
    'godkänn endast nödvändiga cookies',
    'godkänn endast nödvändiga kakor',
    'godta endast nödvändiga',
    'jag godkänner bara nödvändiga kakor',
    'nej, avvisa alla',
    'nej, bara nödvändiga',
    'nej, bara nödvändiga cookies',
    'neka alla utom nödvändiga',
    'neka alla.',
    'neka cookies',
    'neka samtliga',
    'ok, endast nödvändiga',
    'spara endast nödvändiga',
    'stäng och avvisa',
    'tillåt bara nödvändiga',
    'godkänn nödvändiga kakor',
    'godkänn nödvändiga',
    'acceptera nödvändiga',
    'strikt nödvändigt',
    'tillåt nödvändiga',
    'nödvändiga',
    'enbart nödvändiga',
    'jag godkänner nödvändiga kakor',
    'acceptera nödvändiga kakor',
    'godkänn enbart nödvändiga kakor',
    'godkänn nödvändiga cookies',
    'om du inte vill acceptera andra cookies än de som är tekniskt nödvändiga klickar du här',
    'acceptera enbart nödvändiga',
    'nödvändiga cookies',
    'jag godkänner enbart att ni använder nödvändiga cookies',
    '+ strikt nödvändiga cookies',
    'använd enbart nödvändiga cookies',
    'enbart nödvändiga cookies',
    'godkänn nödvändiga kakor stäng',
    'ok till nödvändiga',
    'strikt nödvändiga',
    'fortsätt utan att godkänna',
    'avböj alla cookies',
    'jag accepterar endast grundläggande kakor',
    'nej, jag avböjer',
    'tillåt inte cookies',
];

const REJECT_PATTERNS_POLISH = [
    /^(odrzuć|odrzucenie|odrzucam) (wszystkie|wszystko|wszystkich)$/,
    'odrzuć',
    'odmów',
    'odmowa',
    'odrzucam i chcę dowiedzieć się więcej',
    /^(zaakceptuj )?tylko niezbędne$/,
    'odrzuć opcjonalne',
    'nie zgadzam się',
    'nie wyrażam zgody',
    'odrzucam',
    'kontynuuj bez akceptacji',
    'nie, dziękuję',
    'odmawiam',
    'korzystaj wyłącznie z niezbędnych plików cookie',
    'odrzucać',
    /^funkcjonalne pliki cookie \(wymagane\)$/,
    'odrzuć pliki cookie',
    'tylko wymagane',
    'niezbędne',
    'akceptuj niezbędne',
    'nie akceptuję',
    'kontynuuj bez akceptowania',
    'akceptuj tylko wymagane',
    'rezygnuję',
    'kontynuuj bez wyrażania zgody',
    'tylko wymagane pliki cookie',
    'potwierdzam wymagane',
    'akceptuję wymagane',
    'nie zezwalaj',
    'zezwól tylko na niezbędne',
    'zaakceptuj niezbędne',
    'nie potwierdzam',
    'zezwól na niezbędne',
    'принимать только необходимые файлы cookie',
    'tylko bezwzględnie konieczne',
    'odrzuć nieistotne',
    'akceptuj wymagane',
    'kontynuuj bez akceptowania opcjonalnych cookie',
    'nie',
    'odrzuć niewymagane',
    'tolak cookie',
    'reddet',
    'nie wyrażaj zgody i zamknij',
    'zaakceptuj wymagane',
    'odrzuć wszystkie zgody',
    'odrzuć wszystkie pliki cookies',
    'akceptuj tylko niezbędne',
    'odrzuć wszystkie pliki cookie',
    'odrzuć wszystkie cookies',
    /^odrzucam wszystkie \*$/,
    'tylko niezbędne pliki cookie',
];

/**
 * @type {Array<string|RegExp>}
 */
export const REJECT_PATTERNS = [
    ...REJECT_PATTERNS_ENGLISH,
    ...REJECT_PATTERNS_DUTCH,
    ...REJECT_PATTERNS_FRENCH,
    ...REJECT_PATTERNS_GERMAN,
    ...REJECT_PATTERNS_ITALIAN,
    ...REJECT_PATTERNS_BRAZILIAN_PORTUGUESE,
    ...REJECT_PATTERNS_SPANISH,
    ...REJECT_PATTERNS_SWEDISH,
    ...REJECT_PATTERNS_POLISH,
];

export const NEVER_MATCH_PATTERNS = [
    /pay|subscribe/is,
    /abonneer/is,
    /abonnier/is,
    /abonner/is,
    /abbonati/is,
    /iscriviti/is,
    /abbonare/is,
    /iscrivere/is,
    /sostienici/is,
    /suscribir/is,

    // Spanish (ES)
    /pagar/,
    /suscribirse/,
    /suscribirme/,
    /suscríbete/,
    /^accede gratis con cookies publicitarias$/,
    /suscribo/,
    /^abandonar este sitio$/,

    // Polish (PL)
    /subskrybuj/,
];

export const SETTINGS_PATTERNS = [
    'settings',
    'preferences',
    /customi(s|z)e/is,
    'show details',
    'more options',
    /(manage|configure) (my|your) (preferences|choices|cookies)/is,
    'manage choices',
    /(cookie )?preference center/is,
    'change settings',
    'configure',
    'change my preferences',
    'cookie manager',
    'cookie preference',
    'let me choose',
    'cookieconsent preferences',
    /privacy choices/is,
    /(privacy|cookie|custom) settings/is,
    /cookies? (settings|preferences|setting)/is,
    /(manage|customize|customise|opt-out|edit).*(cookies|preferences|settings|options)/is,
    'cookie consent options',
    'privacy controls',
    'show purposes',
    // German
    'einstellungen',

    // Spanish (ES)
    /^(configurar|configuración|administrar)$/,
    'personalizar',
    'más opciones',
    'gestionar opciones',
    /^(gestionar|ver|establecer) preferencias$/,
    'gestionar cookies',
    'preferencias',
    'mostrar los propósitos',
    /^(konfigurazioa|konfiguratu)$/,
    'mostrar detalles',
    'detalles',
    'ajustes',
    'ajustes de cookies',
    'preferencias de cookies',
    'gestionar mis preferencias',
    'gestión cookies',
    'datenschutzeinstellungen',
    'réglages',
    'gestionar las cookies',
    'configura',
    'gestionar',
    'gestiona tus preferencias',
    'paramétrer vos choix',
    'instellingen',
    'personalize my choices',
    'privatsphäre einstellungen',
    'seleccionar fines individuales',
    'ajustar cookies',
    'veure preferències',
    'no, ajustar',
    'gestión de cookies',
    'configuración de cookies',
    'configurar cookies',
    'personalizar cookies',
    'configurar preferencias',
    'configuración de las cookies',
    'gestionar configuración',
    'configuración cookies',
    'gestionar la configuración de cookies',
    'configuración de cookies y servicios',
    'personalizar mis preferencias',
    'mis preferencias',
    'configuración de cookie',
    'editar la configuración de cookies',
    'administrar cookies',
    'personnaliser',
    'tune configurar',
    'configurar mis preferencias',
    'personalitza',

    // Polish (PL)
    'ustawień zaawansowanych',
    /^(dostosuj|spersonalizuj|chcę dostosować|dostosuj zgody)$/,
    /^(preferencje|zarządzaj preferencjami)$/,
    'więcej opcji',
    /^(zarządzaj cookies|zarządzaj plikami cookie)$/,
    'pokaż cele',
    'skonfiguruj',
    'zobacz preferencje',
    'dostosuj pliki cookie',
    'przejdź do ustawień prywatności',
    'zarządzaj preferencjami plików cookie',
    'zarządzaj zgodami',
    'konfiguracja zgód',
    'przejdź do ustawień',
    'personalizuj pliki cookie',
    'настроить файлы cookie',
    'zarządzaj zgodami dotyczącymi plików cookies',
    /^przejdź do ustawień plików cookies\.$/,
    'dostosuj moje pliki cookie',
    '️ dostosuj',
    'zarządzaj plikami cookie i dowiedz się więcej',
    'zarządzaj plikami cookies',
    'spersonalizuj moje wybory',
    'dostosuj moje wybory',
    'zmień swoje preferencje',
    'zmień zgody',
    'ustaw swoje wybory',
    'dostosuj wybory',
    'pokaż szczegóły',
    'pozwól mi wybrać',
    /^(ustawienia|zmień ustawienia|zmiana ustawień|zarządzaj opcjami)$/,
    'ustawienia plików cookie',
    'ustawienia zaawansowane',
    'ustawienia cookies',
    'ustawieniach plików cookie',
    'ustawienia plików cookies',
    'zarządzaj ustawieniami',
    'dostosuj ustawienia',
    'zarządzaj moimi ustawieniami',
    'zmieniam ustawienia',
    'dostosuj wybór',
    'ustawienia prywatności',
    'ustawienia preferencji',
    'zmieniam zgody',
    'edytuj ustawienia',
    'ustawienia cookie',
    'preferencje cookies',
    'wybierz poszczególne cele',
    'więcej ustawień',
    'pozwól mi wybrać pozwól mi wybrać',
    'zarządzanie preferencjami',
    'ustaw preferencje',
    'podrobné nastavení',
    'ustawienia ciasteczek',
    'zarządzaj',
    'zaawansowane',
    'ustawienia szczegółowe',
    'настройки',
    'ustawienia dotyczące plików cookie i usług',
    'zarządzanie ustawieniami plików cookie',
    'zarządzania zgodami',
    'personalizuj',
    'cookiestatement instellingen',
    'voorkeuren beheren',
    'personalizza cookie',
    'zarządzaj moimi preferencjami',
    'personalizacja',
];

export const ACCEPT_PATTERNS = [
    /^(accept|allow)( all)?( cookies)?$/is,
    /i (accept|allow)( all)?/is,
    'yes',
    /^(i )?agree$/is,
    'continue with all',
    'accept and continue',
    /accept all above/is,
    /^(accept|agree) and close/is,
    'accept continue',
    'agree proceed',
    'allow and continue',
    'close and accept',
    /accept all$/is,
    'im ok with that',
    'accept optional cookies',

    /^alle (cookies )?akzeptieren$/is,

    // Spanish (ES)
    /^acc?ept(ar|o)( cookies)?$/,
    'permitir todas las cookies',
    /^(acc?eptar?|permitir) tod(o|as)$/,
    /^(accetta|aceptar las cookies|accepta)$/,
    'aceptar y cerrar',
    /^aceptar y (continuar|seguir|navegar)( gratis)?$/,
    'aceptar gratis',
    'accetta tutti i cookie',
    /^denak? onartu$/,
    'consentir todo',
    'accepta-les totes',
    'accepta totes les cookies',
    'permetre totes les cookies',
    'consentir',
    'tout accepter',
    'permitir',
    'accepter',
    'akzeptieren',
    'accepta-ho tot',
    'acceptar tot',
    'de acuerdo',
    'de acuerdo y cerrar',
    'estoy de acuerdo',
    'acceptar i tancar',
    'sí, estoy de acuerdo',
    'permitirlas todas',
    'ok, las acepto',
    'permet-les totes',
    /^acept(o|ar) todas las cookies$/,
    'onartu',
    'aceptar cookies opcionales',
    'aceitar',
    'sí, acepto',
    'aceptar y seguir navegando',
    'acceptar galetes',
    'permitir cookies',
    'aceptar todas cookies',

    // Polish (PL)
    /^(akceptuję|akceptuj|zaakceptuj)$/,
    'zgoda',
    /^(akceptuję wszystkie|zaakceptuj zgody)$/,
    'przejdź do serwisu',
    'akceptuję i przechodzę do serwisu',
    'zgadzam się',
    'akceptuj wszystkie',
    'akceptuj wszystko',
    'zezwól na wszystkie',
    'akceptuje wszystkie',
    'zgoda na wszystkie',
    'zaakceptuj i zamknij',
    'akceptuj pliki cookie',
    'potwierdzam wszystkie',
    'ok, zgadzam się',
    'wyrażam zgodę',
    'zezwól',
    'akzeptieren weiter',
    'akceptuję!',
    'akceptuję wszystkie cookies',
    'potwierdzam',
    'accepteren',
    'akceptuję wszystko',
    'akceptuję wszystkie i korzystam z usług',
    'akceptuję wszystkie pliki cookies',
    'akceptuje',
    'akceptuj cookies',
    'принять все файлы cookie',
    'wyraź zgodę na wszystko',
    'akceptuję wszystkie pliki cookie',
    'check akceptuję pliki cookies',
    'akceptuje ciasteczka',
    'włącz wszystkie ciasteczka',
    'zaakceptuj pliki cookies',
    'wyrażam zgodę na wszystkie',
    'zaakceptuj pliki cookie',
    'zezwolenie na wszystkie',
    'tak, zgadzam się na wszystkie pliki cookie',
    'akceptowanie plików cookie',
    'akceptuj i zamknij',
    'akzeptieren und weiter',
    'tak',
    'принять',
    'souhlasím',
    'zaakceptuj wszystkie',
    'akceptuj wszystkie pliki cookie',
    'zaakceptuj wszystko',
    'zaakceptuj i kontynuuj',
    'kabul et',
    'annehmen',
    'zaakceptuj wszystkie zgody i wejdź do serwisu',
    'akceptuję politykę plików cookies i przechodzę do strony',
    'zezwól na wszystkie pliki cookies',
    'zaakceptuj wszystkie pliki cookie',
    'zezwól na wszystkie cookies',
    'zaakceptuj wszystkie i przejdź do serwisu',
    'zaakceptuj wszystkie ciasteczka',
];

export const ACKNOWLEDGE_PATTERNS = [
    'ok',
    'close',
    'continue',
    'x',
    /^got it!?$/,
    'i understand',
    'dismiss',
    'okay',
    'acknowledge',
    /^close (banner|cookie notification)$/is,
    /understood$/is,
    'confirm my choices',

    // Spanish (ES)
    'entendido',
    'dacord',
    'cerca',
    'cerrar',
    'continuar',
    'siguiente',
    'ir al contenido principal',
    'entendido!',
    '¡entendido!',
    'lo entiendo',
    'vale',
    'guardar preferencias',
    'guardar selección',
    'permitir la selección',
    'aceptar selección',
    'seguir',
    'confirmar',
    'aceptar seleccionadas',
    'guardar configuración',

    // Polish (PL)
    'zezwól na wybór',
    'rozumiem',
    'w porządku',
    'zamknij',
    'zamknij informację o plikach cookies',
    'rozumiem!',
    'rozumiem, nie pokazuj więcej',
    'ok, rozumiem',
    'akceptuj wybrane',
    'w porządku!',
    'ok, zrozumiałem',
    'ok rozumiem',
    'ok, rozumiem!',
    'zaakceptuj wybrane',
    'понятно',
    'potwierdź',
    'potwierdzam wybrane',
    'zezwól na wybrane',
    'zgoda na wybrane',
    'kontynuuj',
    'zamknij okno',
    'zapisz i zamknij',
];
