name: 'Setup Release Scripts'
description: 'Install release script dependencies using correct node version'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: 'autoconsent/package-lock.json'
    - run: |
        cd autoconsent
        npm ci
        cd ..
      shell: bash
