#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

export const rulesDir = path.dirname(fileURLToPath(import.meta.url));

async function readFileJSON(filePath) {
    const data = await fs.promises.readFile(filePath, 'utf-8');
    return JSON.parse(data);
}

export async function buildAutoconsentRules() {
    // merge rules from ./autoconsent into rules.autoconsent array
    const autoconsentDir = path.join(rulesDir, 'autoconsent');
    const files = fs.readdirSync(autoconsentDir);
    const generatedRulesDir = path.join(rulesDir, 'generated-rules');
    const generatedFiles = fs.readdirSync(generatedRulesDir);
    const normalRules = await Promise.all(files.map((file) => readFileJSON(path.join(autoconsentDir, file))));
    const autoGeneratedRules = await Promise.all(generatedFiles.map((file) => readFileJSON(path.join(generatedRulesDir, file))));

    // FIXME: this is wip
    const vendorUrls = autoGeneratedRules
        .map(rule => rule.vendorUrl) // Extract vendorUrl from each rule
        .filter(url => !!url); // Filter out rules without a vendorUrl

    // Define the output file path
    const vendorUrlsFilePath = path.join(rulesDir, 'generated-vendor-urls.txt');

    // Write the unique URLs to the file as a JSON array
    try {
        await fs.promises.writeFile(vendorUrlsFilePath, vendorUrls.join('\n'));
        console.log(`Dumped ${vendorUrls.length} unique vendor URLs to ${vendorUrlsFilePath}`);
    } catch (error) {
        console.error(`Error writing vendor URLs file: ${error}`);
    }

    return [...normalRules, ...autoGeneratedRules];
}

export async function buildConsentOMaticRules() {
    // fetch ConsentOMatic rule set and merge with our custom rules
    const consentOMaticCommit = '7d7fd2bd6bf2b662350b0eaeca74db6eba155efe';
    const consentOMaticUrl = `https://raw.githubusercontent.com/cavi-au/Consent-O-Matic/${consentOMaticCommit}/Rules.json`;
    const consentOMaticInclude = ['didomi.io', 'oil', 'optanon', 'quantcast2', 'springer', 'wordpressgdpr'];
    const comRules = {};
    const allComRules = await new Promise((resolve) => {
        https.get(consentOMaticUrl, (res) => {
            res.setEncoding('utf-8');
            let content = '';
            res.on('data', (data) => (content += data));
            res.on('end', () => resolve(JSON.parse(content)));
        });
    });
    consentOMaticInclude.forEach((name) => {
        comRules[name] = allComRules[name];
    });
    return comRules;
}

export function combineRules(autoconsent, consentomatic) {
    return {
        autoconsent,
        consentomatic,
    };
}

(async () => {
    const rules = combineRules(await buildAutoconsentRules(), await buildConsentOMaticRules());
    fs.writeFile(path.join(rulesDir, 'rules.json'), JSON.stringify(rules, undefined, '  '), () => console.log('Written rules.json'));
})();
